[package]
name = "mx-vm-executor-wasmer"
version = "0.0.1"
edition = "2021"

[lib]

[dependencies]
mx-vm-executor = { path = "../exec-service" }

wasmer = { git = "https://github.com/multiversx/wasmer", branch = "instance-reset", default-features = false, features = [
    "singlepass",
    "sys",
    "universal",
    "wat",
] }
wasmer-types = { git = "https://github.com/multiversx/wasmer", branch = "instance-reset" }

loupe = "0.1.3"
