name: libvmexeccapi-build

on:
  push:
    branches:
      - master
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build dynamic library for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            artifact_name: libvmexeccapi.so
            make_target: capi-linux-amd64
          - os: macos-11
            artifact_name: libvmexeccapi.dylib
            make_target: capi-osx-amd64
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
      - name: Make
        run: make ${{ matrix.make_target }}
      - name: Save artifacts
        uses: actions/upload-artifact@v3.1.1
        with:
          name: libs
          path: |
            target/release/*.so
            target/release/*.dylib
            exec-c-api/libvmexeccapi.h
